[project]
name = "idk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "celery[redis]>=5.5.3",
    "django>=5.2.7",
    "redis>=5.2.1",
    "reportlab>=4.4.4",
]
